<a href="https://colab.research.google.com/github/aksaracaa/Data-Analyst/blob/main/Project1/MOVIE_PERFORMANCE_2025_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Import

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy as sp
%matplotlib inline

In [ ]:
plt.style.use('ggplot')

In [ ]:
df = pd.read_csv("movie.csv")

In [ ]:
pd.set_option('display.max_columns', None)

In [ ]:
df.head(5)

,title,release_year,release_month,release_day,genres,rating_out_of_10,vote_count,runtime_minutes,box_office_usd,budget_usd,director,screenwriter,cast,production_company,content_rating,language,country,synopsis,wikipedia_url,poster_url
0,The Mummy Murders,2024,January,2.0,"Horror, Mystery, Thriller",7.8,280952,138,45264640,12501632,NaN,Will Donahue,"Colin Bressler, Leila Annastasia Scott, Jason ...",Gravitas Ventures,R,English,United States,'The Mummy Murders' (2024) is a feature film d...,https://en.wikipedia.org/wiki/The_Mummy_Murders,https://images.unsplash.com/photo-148959984992...
1,DarkGame,2024,January,4.0,"Horror, Mystery, Thriller",7.6,109812,103,40487340,11440392,Howard J. Ford,"Gary Grant,Niall Johnson","Ed Westwick, Andrew P. Stephen, Natalya Tsvetk...",Gravitas Ventures,R,English,United States,'DarkGame' (2024) is a feature film directed b...,https://en.wikipedia.org/wiki/DarkGame,https://images.unsplash.com/photo-148959984992...
2,He Went That Way,2024,January,NaN,"Sci-Fi, Adventure",7.4,234187,128,29375529,22583686,Jeffrey Darling,Evan M. Wiener,"Jacob Elordi,Zachary Quinto,Patrick J. Adams",Vertical Entertainment/Mister Smith Entertainment,PG-13,English,United States,'He Went That Way' (2024) is a feature film di...,https://en.wikipedia.org/wiki/He_Went_That_Way,https://images.unsplash.com/photo-148959984992...
3,The Painter,2024,January,NaN,"Sci-Fi, Adventure",9.2,165532,158,28225644,21817096,Kimani Ray Smith,Brian Buccellato,"Charlie Weber,Jon Voight,Marie Avgeropoulos, M...",Republic Pictures,PG-13,English,United States,'The Painter' (2024) is a feature film directe...,https://en.wikipedia.org/wiki/The_Painter_(202...,https://images.unsplash.com/photo-148959984992...
4,The Bricklayer,2024,January,NaN,"Sci-Fi, Adventure",7.1,227023,92,29255541,22503694,Renny Harlin,"Hanna Weg, Matt Johnson","Aaron Eckhart,Nina Dobrev,Tim Blake Nelson,Ilf...",Vertical Entertainment/Millennium Media,PG-13,English,United States,'The Bricklayer' (2024) is a feature film dire...,https://en.wikipedia.org/wiki/The_Bricklayer,https://images.unsplash.com/photo-148959984992...

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 916 entries, 0 to 915
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   title               916 non-null    object
 1   release_year        916 non-null    int64
 2   release_month       916 non-null    object
 3   release_day         240 non-null    float64
 4   genres              916 non-null    object
 5   rating_out_of_10    916 non-null    float64
 6   vote_count          916 non-null    int64
 7   runtime_minutes     916 non-null    int64
 8   box_office_usd      916 non-null    int64
 9   budget_usd          916 non-null    int64
 10  director            611 non-null    object
 11  screenwriter        894 non-null    object
 12  cast                916 non-null    object
 13  production_company  916 non-null    object
 14  content_rating      916 non-null    object
 15  language            916 non-null    object
 16  country             916 non-null    object
 17  synopsis            916 non-null    object
 18  wikipedia_url       916 non-null    object
 19  poster_url          916 non-null    object
dtypes: float64(2), int64(5), object(13)
memory usage: 143.3+ KB

In [ ]:
df.isnull().sum()

title                   0
release_year            0
release_month           0
release_day           676
genres                  0
rating_out_of_10        0
vote_count              0
runtime_minutes         0
box_office_usd          0
budget_usd              0
director              305
screenwriter           22
cast                    0
production_company      0
content_rating          0
language                0
country                 0
synopsis                0
wikipedia_url           0
poster_url              0
dtype: int64

In [ ]:
df.describe()

,release_year,release_day,rating_out_of_10,vote_count,runtime_minutes,box_office_usd,budget_usd
count,916.000000,240.000000,916.000000,916.000000,916.000000,9.160000e+02,9.160000e+02
mean,2024.975983,15.679167,7.588755,190883.281659,128.033843,4.112292e+07,2.450549e+07
std,0.816143,9.011452,0.959322,97582.137783,21.704472,6.774094e+07,2.138200e+07
min,2024.000000,1.000000,6.000000,7128.000000,90.000000,2.531260e+07,1.084931e+07
25%,2024.000000,7.000000,6.800000,119065.500000,110.750000,2.784818e+07,2.111606e+07
50%,2025.000000,16.000000,7.600000,179263.000000,129.000000,2.908222e+07,2.199819e+07
75%,2026.000000,24.000000,8.400000,253092.000000,146.000000,3.139283e+07,2.302142e+07
max,2026.000000,31.000000,9.200000,452490.000000,164.000000,5.107004e+08,1.712464e+08

# Cleansing Data

## Delete kolom

In [ ]:
# dekete kolom ini karena tidak di perlukan dan banyak yang kosong

df = df.drop(columns=["synopsis","poster_url","wikipedia_url","release_day"])

## Missing Value

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 916 entries, 0 to 915
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   title               916 non-null    object
 1   release_year        916 non-null    int64
 2   release_month       916 non-null    object
 3   genres              916 non-null    object
 4   rating_out_of_10    916 non-null    float64
 5   vote_count          916 non-null    int64
 6   runtime_minutes     916 non-null    int64
 7   box_office_usd      916 non-null    int64
 8   budget_usd          916 non-null    int64
 9   director            611 non-null    object
 10  screenwriter        894 non-null    object
 11  cast                916 non-null    object
 12  production_company  916 non-null    object
 13  content_rating      916 non-null    object
 14  language            916 non-null    object
 15  country             916 non-null    object
dtypes: float64(1), int64(5), object(10)
memory usage: 114.6+ KB

In [ ]:
(df.isna().sum()/df.shape[0])*100

title                  0.000000
release_year           0.000000
release_month          0.000000
genres                 0.000000
rating_out_of_10       0.000000
vote_count             0.000000
runtime_minutes        0.000000
box_office_usd         0.000000
budget_usd             0.000000
director              33.296943
screenwriter           2.401747
cast                   0.000000
production_company     0.000000
content_rating         0.000000
language               0.000000
country                0.000000
dtype: float64

In [ ]:
df[['director', 'screenwriter']]

              director                    screenwriter
0                  NaN                    Will Donahue
1       Howard J. Ford        Gary Grant,Niall Johnson
2      Jeffrey Darling                  Evan M. Wiener
3     Kimani Ray Smith                Brian Buccellato
4         Renny Harlin         Hanna Weg, Matt Johnson
..                 ...                             ...
911        Jake Kasdan    Jeff Pinkner,Scott Rosenberg
912                NaN                            Sjón
913    Jonathan Levine                    Nick Santora
914        Peter Herro  Jennifer Bascom, Deborah Dodge
915  Christopher Nolan               Christopher Nolan

[916 rows x 2 columns]

In [ ]:
df['director'] =  df['director'].fillna('Unknown Director')
df['screenwriter'] = df['screenwriter'].fillna('Unknown Screenwriter')

In [ ]:
print('Missing values director:', df['director'].isna().sum())
print('Missing values screenwriter:', df['screenwriter'].isna().sum())

Missing values director: 0
Missing values screenwriter: 0

In [ ]:
df[
    (df['director']=='Unknown Director') |
    (df['screenwriter']=='Unknown screenwriter')
][['director', 'screenwriter']]

             director                                 screenwriter
0    Unknown Director                                 Will Donahue
14   Unknown Director                   Michael Worth, Hank Hughes
19   Unknown Director                            Carson Bloomquist
21   Unknown Director                                Jamie McGuire
34   Unknown Director  Zach Baylin,Frank E. Flowers,Terence Winter
..                ...                                          ...
892  Unknown Director                                Cambron Clark
902  Unknown Director                               James Pedersen
908  Unknown Director                             Brian K. Vaughan
909  Unknown Director                              Matthew Robbins
912  Unknown Director                                         Sjón

[305 rows x 2 columns]

## Duplikat Data

In [ ]:
duplicate_count = df.duplicated().sum()
print('Jumlah data duplikat:', duplicate_count)

Jumlah data duplikat: 0

## Type Data

In [ ]:
print(df.dtypes)

title                  object
release_year            int64
release_month          object
genres                 object
rating_out_of_10      float64
vote_count              int64
runtime_minutes         int64
box_office_usd          int64
budget_usd              int64
director               object
screenwriter           object
cast                   object
production_company     object
content_rating         object
language               object
country                object
dtype: object

In [ ]:
df['release_year'] = df['release_year'].astype('object')

In [ ]:
print(df.dtypes)

title                  object
release_year           object
release_month          object
genres                 object
rating_out_of_10      float64
vote_count              int64
runtime_minutes         int64
box_office_usd          int64
budget_usd              int64
director               object
screenwriter           object
cast                   object
production_company     object
content_rating         object
language               object
country                object
dtype: object

## Outlier

In [ ]:
import matplotlib.pyplot as plt

numerical_columns = [
    'rating_out_of_10',
    'vote_count',
    'runtime_minutes',
    'box_office_usd',
    'budget_usd'
]

for column in numerical_columns:

    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[
        (df[column] < lower_bound) |
        (df[column] > upper_bound)
    ]
    print(f"\nKolom: {column}")
    print(f"Lower Bound: {lower_bound}")
    print(f"Upper Bound: {upper_bound}")
    print(f"Jumlah Outlier: {len(outliers)}")

Kolom: rating_out_of_10
Lower Bound: 4.399999999999999
Upper Bound: 10.8
Jumlah Outlier: 0

Kolom: vote_count
Lower Bound: -81974.25
Upper Bound: 454131.75
Jumlah Outlier: 0

Kolom: runtime_minutes
Lower Bound: 57.875
Upper Bound: 198.875
Jumlah Outlier: 0

Kolom: box_office_usd
Lower Bound: 22531213.5
Upper Bound: 36709795.5
Jumlah Outlier: 141

Kolom: budget_usd
Lower Bound: 18258007.5
Upper Bound: 25879467.5
Jumlah Outlier: 156

In [ ]:
Q1 = df['box_office_usd'].quantile(0.25)
Q3 = df['box_office_usd'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outlier_box_office = df[
    (df['box_office_usd'] < lower_bound) |
    (df['box_office_usd'] > upper_bound)
]

outlier_box_office[['title', 'box_office_usd']].sort_values(
    by='box_office_usd',
    ascending=False
).head(10)

                               title  box_office_usd
806   Descendants: Wicked Wonderland       510700365
815  Avatar Aang: The Last Airbender       509194275
819        Spider-Man: Brand New Day       501787275
447           Jurassic World Rebirth       501416925
179             Deadpool & Wolverine       498009705
310            Mufasa: The Lion King       497738115
907               Avengers: Doomsday       496602375
615             Avatar: Fire and Ash       496503615
908                 Dune: Part Three       492651975
587                 Wicked: For Good       492392730

In [ ]:
Q1 = df['budget_usd'].quantile(0.25)
Q3 = df['budget_usd'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outlier_budget = df[
    (df['budget_usd'] < lower_bound) |
    (df['budget_usd'] > upper_bound)
]

outlier_budget[['title', 'budget_usd']].sort_values(
    by='budget_usd',
    ascending=False
).head(10)

                               title  budget_usd
806   Descendants: Wicked Wonderland   171246357
815  Avatar Aang: The Last Airbender   170719195
819        Spider-Man: Brand New Day   168126595
447           Jurassic World Rebirth   167996965
179             Deadpool & Wolverine   166804369
310            Mufasa: The Lion King   166709307
907               Avengers: Doomsday   166311775
615             Avatar: Fire and Ash   166277207
908                 Dune: Part Three   164929055
587                 Wicked: For Good   164838314

## Konsistensi Data

In [ ]:
invalid_rating = df[
    (df['rating_out_of_10'] < 0) |
    (df['rating_out_of_10'] > 10)
]

print(invalid_rating[['title', 'rating_out_of_10']])

Empty DataFrame
Columns: [title, rating_out_of_10]
Index: []

In [ ]:
invalid_year = df[
    (df['release_year'].notna()) &
    (
        (df['release_year'] < 1900) |
        (df['release_year'] > 2026)
    )
]

print(invalid_year[['title', 'release_year']])

Empty DataFrame
Columns: [title, release_year]
Index: []

In [ ]:
valid_months = [
    'January', 'February', 'March', 'April',
    'May', 'June', 'July', 'August',
    'September', 'October', 'November', 'December'
]

invalid_month = df[
    ~df['release_month'].isin(valid_months)
]

print(invalid_month[['title', 'release_month']])

Empty DataFrame
Columns: [title, release_month]
Index: []

In [ ]:
categorical_columns = [
    'genres',
    'content_rating',
    'language',
    'country',
    'production_company'
]

for column in categorical_columns:

    print(f"\nKolom: {column}")
    print(df[column].value_counts())

Kolom: genres
genres
Sci-Fi, Adventure                    323
Action, Adventure, Drama, History    118
Drama                                 82
Horror, Mystery, Thriller             58
Animation, Family, Adventure          43
Romance, Drama                        39
Adventure, Drama                      34
Horror, Thriller                      25
Drama, Thriller                       24
Action, Thriller                      22
Mystery, Thriller                     22
Comedy, Drama                         22
Comedy                                22
Musical, Drama                        18
Crime, Drama                          16
Crime, Thriller                       14
Action, Sci-Fi, Superhero             13
Action, Adventure, Drama, Sci-Fi      13
Animation, Family, Comedy              7
Romance, Comedy                        1
Name: count, dtype: int64

Kolom: content_rating
content_rating
PG-13    806
R        105
PG         5
Name: count, dtype: int64

Kolom: language
language
English    916
Name: count, dtype: int64

Kolom: country
country
United States    916
Name: count, dtype: int64

Kolom: production_company
production_company
Vertical                                                25
Netflix                                                 15
Quiver Distribution                                     14
Lionsgate                                               12
Saban Films                                             11
                                                        ..
TriStar Pictures/Hoorae Media                            1
Paramount+/Nickelodeon Productions/Awesomeness Films     1
Different Duck Films                                     1
Lionsgate/Davis Entertainment/Icon Productions           1
Roadside Attractions/Utopia/Pinky Promise                1
Name: count, Length: 663, dtype: int64

# EDA

## ROI & PROFIT

In [ ]:
# menghitung profit
df['profit'] = df['box_office_usd'] - df['budget_usd']

# menghitung ROI
df['ROI'] = (
    (df['box_office_usd'] - df['budget_usd'])
    / df['budget_usd']
) * 100

In [ ]:
df.head(5)

,title,release_year,release_month,genres,rating_out_of_10,vote_count,runtime_minutes,box_office_usd,budget_usd,director,screenwriter,cast,production_company,content_rating,language,country,profit,ROI
0,The Mummy Murders,2024,January,"Horror, Mystery, Thriller",7.8,280952,138,45264640,12501632,Unknown Director,Will Donahue,"Colin Bressler, Leila Annastasia Scott, Jason ...",Gravitas Ventures,R,English,United States,32763008,262.069848
1,DarkGame,2024,January,"Horror, Mystery, Thriller",7.6,109812,103,40487340,11440392,Howard J. Ford,"Gary Grant,Niall Johnson","Ed Westwick, Andrew P. Stephen, Natalya Tsvetk...",Gravitas Ventures,R,English,United States,29046948,253.898188
2,He Went That Way,2024,January,"Sci-Fi, Adventure",7.4,234187,128,29375529,22583686,Jeffrey Darling,Evan M. Wiener,"Jacob Elordi,Zachary Quinto,Patrick J. Adams",Vertical Entertainment/Mister Smith Entertainment,PG-13,English,United States,6791843,30.074112
3,The Painter,2024,January,"Sci-Fi, Adventure",9.2,165532,158,28225644,21817096,Kimani Ray Smith,Brian Buccellato,"Charlie Weber,Jon Voight,Marie Avgeropoulos, M...",Republic Pictures,PG-13,English,United States,6408548,29.373974
4,The Bricklayer,2024,January,"Sci-Fi, Adventure",7.1,227023,92,29255541,22503694,Renny Harlin,"Hanna Weg, Matt Johnson","Aaron Eckhart,Nina Dobrev,Tim Blake Nelson,Ilf...",Vertical Entertainment/Millennium Media,PG-13,English,United States,6751847,30.003283

## 1

1. Film dengan box office tertinggi

In [ ]:
top_10_revanue = df.sort_values(
    by='box_office_usd',
    ascending=False
).head(10)

print(top_10_revanue[
    ['title', 'box_office_usd', 'production_company']
])

                               title  box_office_usd  \
806   Descendants: Wicked Wonderland       510700365
815  Avatar Aang: The Last Airbender       509194275
819        Spider-Man: Brand New Day       501787275
447           Jurassic World Rebirth       501416925
179             Deadpool & Wolverine       498009705
310            Mufasa: The Lion King       497738115
907               Avengers: Doomsday       496602375
615             Avatar: Fire and Ash       496503615
908                 Dune: Part Three       492651975
587                 Wicked: For Good       492392730

                                    production_company
806                             Disney Channel/Disney+
815  Paramount+/Paramount Pictures/Nickelodeon Movi...
819   Columbia Pictures/Marvel Studios/Pascal Pictures
447            Universal Pictures/Amblin Entertainment
179  Marvel Studios/Maximum Effort/21 Laps Entertai...
310                               Walt Disney Pictures
907                                Marvel Studios/AGBO
615      20th Century Studios/Lightstorm Entertainment
908           Warner Bros. Pictures/Legendary Pictures
587          Universal Pictures/Marc Platt Productions

## 2

2. Pendapatan tertinggi

In [ ]:
#Genre yang menghasilkan pendapatan tertinggi

genre_df = df.copy()
genre_df['genres'] = genre_df['genres'].str.split(', ')
genre_df = genre_df.explode('genres')

genre_revenue = (
    genre_df.groupby('genres')['box_office_usd'].sum().sort_values(ascending=False)

)
print(genre_revenue)

genres
Adventure    22589985465
Drama        14912535843
Sci-Fi       13545529605
Action       10058395239
Thriller      6330431875
History       6295693326
Animation     4240119186
Family        4240119186
Horror        3614679350
Mystery       3509693460
Comedy        1975860066
Superhero     1793657628
Romance       1178307498
Musical        997342299
Crime          897517578
Name: box_office_usd, dtype: int64

In [ ]:
# Tahun dengan pendapatan film terbesar
year_revenue = (
    df.groupby('release_year')['box_office_usd'].sum().sort_values(ascending=False)
)
print(year_revenue)

release_year
2024    13492212456
2026    12388313125
2025    11788070205
Name: box_office_usd, dtype: int64

In [ ]:
# Bulan dengan pendapatan film terbesar
month__avg_revenue = (
    df.groupby('release_month')['box_office_usd'].mean().sort_values(ascending=False)
)
print(month__avg_revenue)

release_month
July         8.372691e+07
December     6.246843e+07
November     5.714931e+07
June         4.437050e+07
March        3.703817e+07
May          3.183148e+07
September    3.161190e+07
April        3.122299e+07
October      3.093681e+07
January      3.089462e+07
February     3.072231e+07
August       3.012088e+07
Name: box_office_usd, dtype: float64

## 3

3. Analisis Rating film

In [ ]:
print(df['rating_out_of_10'].describe())

count    916.000000
mean       7.588755
std        0.959322
min        6.000000
25%        6.800000
50%        7.600000
75%        8.400000
max        9.200000
Name: rating_out_of_10, dtype: float64

In [ ]:
genre_rating = (
    genre_df.groupby('genres')['rating_out_of_10'].mean().sort_values(ascending=False)
)

print(genre_rating.head(10))

genres
Thriller     7.699394
Action       7.674096
Horror       7.673494
Mystery      7.671250
History      7.657627
Sci-Fi       7.631519
Adventure    7.621092
Animation    7.570000
Family       7.570000
Drama        7.539617
Name: rating_out_of_10, dtype: float64

In [ ]:
correlation = df[
    ['rating_out_of_10', 'box_office_usd']
].corr()

print("correlation:", correlation)

correlation:                   rating_out_of_10  box_office_usd
rating_out_of_10          1.000000        0.002792
box_office_usd            0.002792        1.000000

Berdasarkan analisis korelasi, hubungan antara rating film dan pendapatan box office menunjukkan nilai korelasi sebesar 0.0028, yang sangat mendekati nol. Hal ini menunjukkan bahwa rating film tidak memiliki hubungan linear yang signifikan dengan pendapatan box office pada dataset ini. Dengan demikian, rating yang tinggi belum tentu menghasilkan pendapatan yang tinggi.

## 4

4. Budget vs box office

In [ ]:
budget_revenue_corr = df['budget_usd'].corr(
    df['box_office_usd']
)

print(
    "Correlation Budget vs Box Office:",
    budget_revenue_corr
)

Correlation Budget vs Box Office: 0.9735719702513093

Berdasarkan analisis korelasi, hubungan antara rating film dan pendapatan box office menunjukkan nilai korelasi sebesar 0.9735, yang sangat mendekati 1. Hal ini menunjukkan bahwa budget lebih tinggi menghasilkan box office lebih tinggi.

## 5

5. Analisis ROI

In [ ]:
top_roi = df.sort_values(
    by='ROI',
    ascending=False
)

print(
    top_roi[
        [
            'title',
            'budget_usd',
            'box_office_usd',
            'profit',
            'ROI'
        ]
    ].head(10)
)

                               title  budget_usd  box_office_usd    profit  \
274  Christmas Eve in Miller's Point    14029324        52141730  38112406
501  Downton Abbey: The Grand Finale    13936774        51725105  37788331
342  The Witcher: Sirens of the Deep    13925668        51675110  37749442
453  Zombies 4: Dawn of the Vampires    13912094        51614005  37701911
834    Insidious: Out of the Further    13855330        51358475  37503145
610  The Mother, the Menacer, and Me    13787460        51052950  37265490
73       Ghostbusters: Frozen Empire    13771418        50980735  37209317
747      Remarkably Bright Creatures    13767716        50964070  37196354
494        The Conjuring: Last Rites    13348156        49075370  35727214
238        The Curse of the Necklace    13280286        48769845  35489559

            ROI
274  271.662455
501  271.141162
342  271.078141
453  271.000979
834  270.676664
610  270.285390
73   270.192343
747  270.170840
494  267.656551
238  267.234900

In [ ]:
print(df['ROI'].describe())

count    916.000000
mean      59.842737
std       75.752826
min       27.358568
25%       29.133294
50%       29.900080
75%       31.194014
max      271.662455
Name: ROI, dtype: float64

## 6

6. Studio dengan penghasilan revenue terbesar

In [ ]:
studio_df = df.copy()

studio_df['production_company'] = (
    studio_df['production_company']
    .str.split('/')
)

studio_df = studio_df.explode('production_company')

studio_df['production_company'] = (
    studio_df['production_company']
    .str.strip()
)

In [ ]:
studio_revenue = (
    studio_df.groupby('production_company')['box_office_usd']
    .sum()
    .sort_values(ascending=False)
)

print(studio_revenue.head(10))

production_company
Universal Pictures       3406177226
Walt Disney Pictures     2767304547
Netflix                  2589219790
Warner Bros. Pictures    2245492933
Paramount Pictures       2003735170
Lionsgate                1802556537
Marvel Studios           1594221639
Vertical                 1556568104
Columbia Pictures        1209588192
Legendary Pictures       1144946097
Name: box_office_usd, dtype: int64

In [ ]:
studio_analysis = (
    studio_df.groupby('production_company')
    .agg(
        average_rating=('rating_out_of_10', 'mean'),
        movie_count=('title', 'count')
    )
)

studio_analysis = studio_analysis[
    studio_analysis['movie_count'] >= 5
]

studio_analysis = studio_analysis.sort_values(
    by='average_rating',
    ascending=False
)

print(studio_analysis.head(10))

                                average_rating  movie_count
production_company
Ley Line Entertainment                8.266667            6
Anonymous Content                     8.242857            7
Blue Harbor Entertainment             8.180000            5
Blumhouse Productions                 8.090909           11
Warner Bros. Animation                8.080000            5
Screen Gems                           8.060000            5
Sony Pictures Classics                8.028571            7
Grindstone Entertainment Group        8.022222            9
Bleecker Street                       8.021429           14
Scott Free Productions                8.020000            5

In [ ]:
df.to_csv('movie_cleaned.csv', index=False)

# SQL

In [ ]:
!pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-26.7.0-cp313-cp313-manylinux_2_28_x86_64.whl.metadata (11 kB)
Downloading mysql_connector_python-26.7.0-cp313-cp313-manylinux_2_28_x86_64.whl (21.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.7/21.7 MB 34.1 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-26.7.0

In [ ]:
import mysql.connector
import pandas as pd

In [ ]:
!pip install duckdb

Requirement already satisfied: duckdb in /usr/local/lib/python3.13/dist-packages (1.3.2)

In [ ]:
import sqlite3

# Membuat database sementara di Colab
conn = sqlite3.connect(":memory:")

# Memasukkan dataframe menjadi tabel SQL bernama movies
df.to_sql("movies", conn, index=False, if_exists="replace")

916

In [ ]:
query = """
SELECT *
FROM movies
LIMIT 10;
"""

pd.read_sql(query, conn)

,title,release_year,release_month,genres,rating_out_of_10,vote_count,runtime_minutes,box_office_usd,budget_usd,director,screenwriter,cast,production_company,content_rating,language,country,profit,ROI
0,The Mummy Murders,2024,January,"Horror, Mystery, Thriller",7.8,280952,138,45264640,12501632,Unknown Director,Will Donahue,"Colin Bressler, Leila Annastasia Scott, Jason ...",Gravitas Ventures,R,English,United States,32763008,262.069848
1,DarkGame,2024,January,"Horror, Mystery, Thriller",7.6,109812,103,40487340,11440392,Howard J. Ford,"Gary Grant,Niall Johnson","Ed Westwick, Andrew P. Stephen, Natalya Tsvetk...",Gravitas Ventures,R,English,United States,29046948,253.898188
2,He Went That Way,2024,January,"Sci-Fi, Adventure",7.4,234187,128,29375529,22583686,Jeffrey Darling,Evan M. Wiener,"Jacob Elordi,Zachary Quinto,Patrick J. Adams",Vertical Entertainment/Mister Smith Entertainment,PG-13,English,United States,6791843,30.074112
3,The Painter,2024,January,"Sci-Fi, Adventure",9.2,165532,158,28225644,21817096,Kimani Ray Smith,Brian Buccellato,"Charlie Weber,Jon Voight,Marie Avgeropoulos, M...",Republic Pictures,PG-13,English,United States,6408548,29.373974
4,The Bricklayer,2024,January,"Sci-Fi, Adventure",7.1,227023,92,29255541,22503694,Renny Harlin,"Hanna Weg, Matt Johnson","Aaron Eckhart,Nina Dobrev,Tim Blake Nelson,Ilf...",Vertical Entertainment/Millennium Media,PG-13,English,United States,6751847,30.003283
5,Some Other Woman,2024,January,"Adventure, Drama",8.2,255480,160,29732160,22821440,Joel David Moore,"Yuri Baranovsky, Angela Gulner, Josh Long","Amanda Crew,Tom Felton,Ashley Greene",Radiant Films International / Balcony 9 Produc...,PG-13,English,United States,6910720,30.281700
6,We Strangers,2024,January,"Drama, Thriller",8.9,191203,137,28655601,22103734,Anu Valia,Unknown Screenwriter,"Kirby Howell-Baptiste,Tina Lifford,Sarah Goldb...","Pigasus Pictures, Wingate Media, Mirmade, Kill...",PG-13,English,United States,6551867,29.641449
7,The Beekeeper,2024,January,"Action, Adventure, Drama, History",7.5,201551,114,28828917,22219278,David Ayer,Kurt Wimmer,"Jason Statham,Emmy Raver-Lampman,Josh Hutchers...",Metro-Goldwyn-Mayer/Miramax,PG-13,English,United States,6609639,29.747317
8,Mean Girls,2024,January,"Musical, Drama",7.7,142846,119,27845682,21563788,"Arturo Perez Jr., Samantha Jayne",Tina Fey,"Angourie Rice,Reneé Rapp,Auliʻi Cravalho,Jaque...",Paramount Pictures/Broadway Video/Little Stranger,PG-13,English,United States,6281894,29.131681
9,Lift,2024,January,"Romance, Drama",7.4,37177,113,26075859,20383906,F. Gary Gray,Daniel Kunka,"Kevin Hart,Gugu Mbatha-Raw,Vincent D’Onofrio,Ú...",Netflix/Genre Films/6th & Idaho Productions,PG-13,English,United States,5691953,27.923760

In [ ]:
query = """
SELECT COUNT(*) AS total_movie
FROM movies;
"""

pd.read_sql(query, conn)

   total_movie
0          916

In [ ]:
query = """
SELECT genres,
       COUNT(*) AS total_movie
FROM movies
GROUP BY genres
ORDER BY total_movie DESC;
"""

pd.read_sql(query, conn)

                               genres  total_movie
0                   Sci-Fi, Adventure          323
1   Action, Adventure, Drama, History          118
2                               Drama           82
3           Horror, Mystery, Thriller           58
4        Animation, Family, Adventure           43
5                      Romance, Drama           39
6                    Adventure, Drama           34
7                    Horror, Thriller           25
8                     Drama, Thriller           24
9                   Mystery, Thriller           22
10                      Comedy, Drama           22
11                             Comedy           22
12                   Action, Thriller           22
13                     Musical, Drama           18
14                       Crime, Drama           16
15                    Crime, Thriller           14
16          Action, Sci-Fi, Superhero           13
17   Action, Adventure, Drama, Sci-Fi           13
18          Animation, Family, Comedy            7
19                    Romance, Comedy            1

In [ ]:
query = """
SELECT title,
       box_office_usd
FROM movies
ORDER BY box_office_usd DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

                             title  box_office_usd
0   Descendants: Wicked Wonderland       510700365
1  Avatar Aang: The Last Airbender       509194275
2        Spider-Man: Brand New Day       501787275
3           Jurassic World Rebirth       501416925
4             Deadpool & Wolverine       498009705
5            Mufasa: The Lion King       497738115
6               Avengers: Doomsday       496602375
7             Avatar: Fire and Ash       496503615
8                 Dune: Part Three       492651975
9                 Wicked: For Good       492392730

In [ ]:
query = """
SELECT genres,
       ROUND(AVG(rating_out_of_10),2) AS avg_rating
FROM movies
GROUP BY genres
ORDER BY avg_rating DESC;
"""

pd.read_sql(query, conn)

                               genres  avg_rating
0                    Action, Thriller        7.90
1                     Drama, Thriller        7.83
2    Action, Adventure, Drama, Sci-Fi        7.73
3           Horror, Mystery, Thriller        7.69
4   Action, Adventure, Drama, History        7.66
5                   Sci-Fi, Adventure        7.64
6                    Horror, Thriller        7.64
7                   Mystery, Thriller        7.63
8        Animation, Family, Adventure        7.60
9                               Drama        7.53
10                    Crime, Thriller        7.41
11                     Romance, Drama        7.40
12                      Comedy, Drama        7.40
13          Action, Sci-Fi, Superhero        7.38
14          Animation, Family, Comedy        7.37
15                     Musical, Drama        7.35
16                       Crime, Drama        7.34
17                             Comedy        7.32
18                   Adventure, Drama        7.32
19                    Romance, Comedy        6.90